apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: goldentest
  title: goldentest
  description: Golden path test
  tags:
    - go
  annotations:
    github.com/project-slug: biniter1/goldentest
    backstage.io/kubernetes-id: goldentest
    backstage.io/kubernetes-namespace: goldentest
    argocd/app-name: goldentest
spec:
  type: service
  lifecycle: development
  owner: devops-team
  system: online-boutique
